import React from "react";
import "./global.css";
import { Box } from "@mui/material";
import { Header, Footer } from "./components/layout";

export const metadata = {
  title: "Welcome to frontend",
  description: "Generated by create-nx-workspace"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Ads project</title>
      </head>
      <body>
        <Header />
        <Box component="main">{children}</Box>
        <Footer />
      </body>
    </html>
  );
}
