import React, { ReactNode } from "react";
import "./global.css";
import { Box } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import ToastProvider from "../providers/toast";
import theme from "../providers/mui";
import { Header, Footer } from "../components/layout";

export const metadata = {
  title: "Welcome to frontend",
  description: "Generated by create-nx-workspace"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Ads project</title>
      </head>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <ToastProvider>
              <Header />
              <Box component="main" sx={{ minHeight: "100vh" }}>
                {children}
              </Box>
              <Footer />
            </ToastProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
